---
# Example command to execute with tags: ansible-playbook install_apache_httpd_with_tags.yml --tags "install apache"
#  ansible-playbook install_apache_httpd_with_tags.yml --tags "install apache"
#   ansible-playbook install_apache_httpd_with_tags.yml --tags "start apache"
- name: to install the httpd and start the service using the tags filter
  hosts: all
  become: True

  tasks:
    - name: installing httpd
      yum:
        name: httpd
        state: installed
      when: ansible_os_family == "RedHat"
      tags: "install apache"

    - name: start httpd service
      service:
        name: httpd
        state: started
      when: ansible_os_family == "RedHat"
      tags: "start apache"

    - name: installing apache2
      apt:
        name: apache2
        state: present
      when: ansible_os_family == "Debian"
      tags: "install apache"

    - name: start apache2 service
      service:
        name: apache2
        state: started
      when: ansible_os_family == "Debian"
      tags: "start apache"

    - name: copy index.html
      copy:
        src: /opt/ansible/index.html
        dest: /var/www/html
        mode: 0666


