---
- name: to install the apache2 on ubuntu server
  hosts: dbservers
  become: True

  tasks:
    - name: installing apache2
      apt: 
        name: apache2
        state: present
    - name: start apache2 service
      service:
        name: apache2
        state: started
